version: '3.8'

services:
  app:
    container_name: react-app
    build: .
    depends_on:
      - database
      # context: ./
      # dockerfile: Dockerfile
    volumes:
      - './:/usr/src/app'
    ports:
      - "8080:8080"

  database:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - './database/init:/docker-entrypoint-initdb.d/'
 